### ISSUE TITLE
BUG: too many hipsters, too much plaid

### ISSUE THREAD

**Issue by megberetta** [cds-snc/training-repo#27]
Please fix all the plaid in the hipster world

**Comment by megberetta** [comment]
Got it, stripes only.

**Comment by DaveToeg** [comment]
I would suggest changing the plaid to tartan!

**Comment by megberetta** [comment]
Dave, you're not involved.

**Comment by DaveToeg** [comment]
Then someone shouldn't have made this repo public!! 😉
